// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/recommend.proto

package invoicer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductIds    string                 `protobuf:"bytes,2,opt,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductRequest) Reset() {
	*x = ProductRequest{}
	mi := &file_proto_recommend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductRequest) ProtoMessage() {}

func (x *ProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recommend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductRequest.ProtoReflect.Descriptor instead.
func (*ProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_recommend_proto_rawDescGZIP(), []int{0}
}

func (x *ProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductRequest) GetProductIds() string {
	if x != nil {
		return x.ProductIds
	}
	return ""
}

func (x *ProductRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ProductRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ScoreItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreItem) Reset() {
	*x = ScoreItem{}
	mi := &file_proto_recommend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreItem) ProtoMessage() {}

func (x *ScoreItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recommend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreItem.ProtoReflect.Descriptor instead.
func (*ScoreItem) Descriptor() ([]byte, []int) {
	return file_proto_recommend_proto_rawDescGZIP(), []int{1}
}

func (x *ScoreItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScoreItem) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     string                 `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_proto_recommend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recommend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_proto_recommend_proto_rawDescGZIP(), []int{2}
}

func (x *ErrorResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ErrorResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ScoreItem           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Error         *ErrorResponse         `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	TotalPages    int32                  `protobuf:"varint,3,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductResponse) Reset() {
	*x = ProductResponse{}
	mi := &file_proto_recommend_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductResponse) ProtoMessage() {}

func (x *ProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recommend_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductResponse.ProtoReflect.Descriptor instead.
func (*ProductResponse) Descriptor() ([]byte, []int) {
	return file_proto_recommend_proto_rawDescGZIP(), []int{3}
}

func (x *ProductResponse) GetItems() []*ScoreItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ProductResponse) GetError() *ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ProductResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

var File_proto_recommend_proto protoreflect.FileDescriptor

const file_proto_recommend_proto_rawDesc = "" +
	"\n" +
	"\x15proto/recommend.proto\x12\x0erecommendation\"\x81\x01\n" +
	"\x0eProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1f\n" +
	"\vproduct_ids\x18\x02 \x01(\tR\n" +
	"productIds\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"1\n" +
	"\tScoreItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\"S\n" +
	"\rErrorResponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x98\x01\n" +
	"\x0fProductResponse\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.recommendation.ScoreItemR\x05items\x123\n" +
	"\x05error\x18\x02 \x01(\v2\x1d.recommendation.ErrorResponseR\x05error\x12\x1f\n" +
	"\vtotal_pages\x18\x03 \x01(\x05R\n" +
	"totalPages2\xc0\x01\n" +
	"\x15RecommendationService\x12W\n" +
	"\x14RecommendByProductId\x12\x1e.recommendation.ProductRequest\x1a\x1f.recommendation.ProductResponse\x12N\n" +
	"\vListSimilar\x12\x1e.recommendation.ProductRequest\x1a\x1f.recommendation.ProductResponseB\x19Z\x17invoicer/recommendationb\x06proto3"

var (
	file_proto_recommend_proto_rawDescOnce sync.Once
	file_proto_recommend_proto_rawDescData []byte
)

func file_proto_recommend_proto_rawDescGZIP() []byte {
	file_proto_recommend_proto_rawDescOnce.Do(func() {
		file_proto_recommend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_recommend_proto_rawDesc), len(file_proto_recommend_proto_rawDesc)))
	})
	return file_proto_recommend_proto_rawDescData
}

var file_proto_recommend_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_recommend_proto_goTypes = []any{
	(*ProductRequest)(nil),  // 0: recommendation.ProductRequest
	(*ScoreItem)(nil),       // 1: recommendation.ScoreItem
	(*ErrorResponse)(nil),   // 2: recommendation.ErrorResponse
	(*ProductResponse)(nil), // 3: recommendation.ProductResponse
}
var file_proto_recommend_proto_depIdxs = []int32{
	1, // 0: recommendation.ProductResponse.items:type_name -> recommendation.ScoreItem
	2, // 1: recommendation.ProductResponse.error:type_name -> recommendation.ErrorResponse
	0, // 2: recommendation.RecommendationService.RecommendByProductId:input_type -> recommendation.ProductRequest
	0, // 3: recommendation.RecommendationService.ListSimilar:input_type -> recommendation.ProductRequest
	3, // 4: recommendation.RecommendationService.RecommendByProductId:output_type -> recommendation.ProductResponse
	3, // 5: recommendation.RecommendationService.ListSimilar:output_type -> recommendation.ProductResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_recommend_proto_init() }
func file_proto_recommend_proto_init() {
	if File_proto_recommend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_recommend_proto_rawDesc), len(file_proto_recommend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_recommend_proto_goTypes,
		DependencyIndexes: file_proto_recommend_proto_depIdxs,
		MessageInfos:      file_proto_recommend_proto_msgTypes,
	}.Build()
	File_proto_recommend_proto = out.File
	file_proto_recommend_proto_goTypes = nil
	file_proto_recommend_proto_depIdxs = nil
}
