
services:
  qdrant:
    container_name: ${VERTORDB_SERVICE_NAME}
    image: qdrant/qdrant:v1.11.5  
    ports:
      - "${QDRANT_HTTP}:${QDRANT_HTTP}"
      - "${QDRANT_gRPC}:${QDRANT_gRPC}"
    volumes:
      - qdrant_data:/qdrant/storage
    env_file:
      - .env
    networks:
      - movie_provider

  recomgo-service:
    container_name: ${RECOMGO_SERVICE_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${RECOMGO_SERVICE_PORT}:${RECOMGO_SERVICE_PORT}"
    depends_on:
      - qdrant
    env_file:
      - .env
    networks:
      - movie_provider
    
volumes:
  qdrant_data:


networks:
  movie_provider:
    name: movie_provider
    external: true