
services:
  go-recommend-service:
    container_name: go-recommend-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8386:8386"
    env_file:
      - .env
    networks:
      - retrade-agent


networks:
  retrade-agent:
    name: retrade-agent