services:
  product-image-search-services:
    image: ${REGISTRY}/rt-product-image-search:latest
    build:
      context: ../product-image-search
      dockerfile: Dockerfile
      tags:
        - ${REGISTRY}/rt-product-image-search:${TAG}
    profiles:
      - agent
      - build
      - product-image-search
  text-moderation-services:
    image: ${REGISTRY}/rt-text-moderation:latest
    build:
      context: ../text-moderation
      dockerfile: Dockerfile
      tags:
        - ${REGISTRY}/rt-text-moderation:${TAG}
    profiles:
      - agent
      - build
      - text-moderation

  mage-ai:
    image: ${REGISTRY}/rt-mageai:latest
    build:
      context: ../mage-ai
      dockerfile: Dockerfile
      tags:
        - ${REGISTRY}/rt-mageai:${TAG}
    profiles:
      - agent
      - build
      - mageai
  
  go-recommender:
    image: ${REGISTRY}/rt-go-recommender:latest
    build:
      context: ../go-recommend
      dockerfile: Dockerfile
      tags:
        - ${REGISTRY}/rt-go-recommender:${TAG}
    profiles:
      - agent
      - build
      - go-recommender

  province-services:
    image: ${REGISTRY}/vn-province:latest
    build:
      context: ../provinces
      dockerfile: Dockerfile
    profiles:
      - agent
      - build
      - province
  
  identity-ocr:
    image: ${REGISTRY}/identity-ocr:latest
    build:
      context: ../identity-ocr
      dockerfile: Dockerfile
    profiles:
      - agent
      - build
      - identity-ocr