services:
  product-image-search-services:
    build:
      context: ../product-image-search
      dockerfile: Dockerfile
      tags:
        - ${REGISTRY}/rt-product-image-search:latest
        - ${REGISTRY}/rt-product-image-search:${TAG}
    profiles:
      - agent
      - build
      - product-image-search
  text-moderation-services:
    build:
      context: ../text-moderation
      dockerfile: Dockerfile
      tags:
        - ${REGISTRY}/rt-text-moderation:latest
        - ${REGISTRY}/rt-text-moderation:${TAG}
    profiles:
      - agent
      - build
      - text-moderation

  mage-ai:
    build:
      context: ../mage-ai
      dockerfile: Dockerfile
      tags:
        - ${REGISTRY}/rt-mageai:latest
        - ${REGISTRY}/rt-mageai:${TAG}
    profiles:
      - agent
      - build
      - mageai