services:
  product-image-search-services:
    image: ${REGISTRY}/product-image-search
    build:
      context: ..
      dockerfile: product-image-search/Dockerfile
      tags:
        - ${REGISTRY}/rt-product-image-search:latest
        - ${REGISTRY}/rt-product-image-search:${TAG}
    profiles:
      - agent
      - build
      - product-image-search
  text-moderation-services:
    image: ${REGISTRY}/rt-text-moderation
    build:
      context: ..
      dockerfile: text-moderation/Dockerfile
      tags:
        - ${REGISTRY}/rt-text-moderation:latest
        - ${REGISTRY}/rt-text-moderation:${TAG}
    profiles:
      - agent
      - build
      - text-moderation