services:
  product-image-search-services:
    image: ${REGISTRY}/product-image-search:latest
    restart: always
    container_name: rt-product-image-search
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      APP_PORT: 9090
      APP_HOST: 0.0.0.0
      QDRANT_URL: http://retrade-qdrant:6333
      QDRANT_COLLECTION_NAME: retrade-product
      DEBUG: True
      TZ: Asia/Ho_Chi_Minh
      APP_API_KEY: ${APP_API_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.image-search.rule=PathPrefix(`/api/image-search/v1/`)"
      - "traefik.http.routers.image-search.entrypoints=web"
      - "traefik.http.middlewares.strip-image-search-prefix.stripprefix.prefixes=/api/image-search/v1"
      - "traefik.http.routers.image-search.middlewares=strip-image-search-prefix"
      - "traefik.docker.network=retrade-network"
      - "traefik.constraint-label=retrade-service"
      - "traefik.http.services.image-search.loadbalancer.server.port=9090"
    networks:
      - retrade-network
    profiles:
      - agent
      - prod
      - product-image-search
  text-moderation-services:
    image: ${REGISTRY}/rt-text-moderation
    restart: always
    container_name: rt-text-moderation
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      COMMENT_PORT: 8888
      TZ: Asia/Ho_Chi_Minh
    networks:
      - retrade-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.text-moderation.rule=PathPrefix(`/api/text-moderation/v1/`)"
      - "traefik.http.routers.text-moderation.entrypoints=web"
      - "traefik.http.middlewares.strip-text-moderation-prefix.stripprefix.prefixes=/api/text-moderation/v1"
      - "traefik.http.routers.text-moderation.middlewares=strip-text-moderation-prefix"
      - "traefik.docker.network=retrade-network"
      - "traefik.constraint-label=retrade-service"
      - "traefik.http.services.text-moderation.loadbalancer.server.port=8888"
    profiles:
      - agent
      - prod
      - text-moderation

networks:
  retrade-network:
    name: retrade-network
    external: true