version: '3.8'

services:
  comment_review-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=8001
    restart: always
